#!/bin/sh
#
# Startup / shutdown script for the sentinel daemon
#
# Copyright (c) 2011, FunPlus, Inc.
# All rights reserved
#
#
### BEGIN INIT INFO
# Provides:          sentinel
# Required-Start:    $network $local_fs
# Required-Stop:
# Should-Start:      $named
# Should-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    sentinel daemon
# Description:          sentinel daemon

### END INIT INFO

. /etc/init.d/functions

if [ "$(id -u)" != "0" ]; then
    echo "Must run as root"
    exit 1
fi

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

SENTINEL_HOME=/var/wd/sentinel
DAEMON=$SENTINEL_HOME/bin/sentinel
CONFIGFILE=$SENTINEL_HOME/etc/sentinel.cf
LOGFILE=$SENTINEL_HOME/var/sentinel.log
CRASHLOG=$SENTINEL_HOME/panic.dump
LOCKFILE=$SENTINEL_HOME/var/sentinel.pid

test -f $DAEMON || exit 0
test -f $CONFIGFILE || exit 0

# Otherwise, RHEL (and apparently Fedora) tries to "help" and set soft
# limit of core file size to 0 for daemons. It's done as part of
# daemon shell function shortly after changing user. See MB-6601
DAEMON_COREFILE_LIMIT=unlimited

start() {
    cd $SENTINEL_HOME
    ulimit -n 40960
    ulimit -c unlimited
    ulimit -l unlimited
    daemon "/usr/sbin/daemonize $DAEMON -conf $CONFIGFILE -crashlog $CRASHLOG -log $LOGFILE -lockfile $LOCKFILE -level trace"
    errcode=$?
    return $errcode
}

stop() {
    daemon "$DAEMON -k -lockfile $LOCKFILE -conf $CONFIGFILE"
    errcode=$?
    return $errcode
}

running() {
    pidofproc -p $LOCKFILE $DAEMON >/dev/null
    errcode=$?
    return $errcode
}

case $1 in
    start)
        running
        running=$?
        if [[ $(running) || -f "$LOCKFILE" ]] ; then
            warning && echo "sentinel-daemon is already started"
            exit 0
        fi
        echo -n $"Starting sentinel-daemon"
        start
        echo
        ;;
    stop)
        echo -n $"Stopping sentinel-daemon"
        stop
        echo
        ;;
    restart)
        echo -n $"Stopping sentinel-daemon"
        stop
        echo
        echo -n $"Starting sentinel-daemon"
        start
        echo
        ;;
    status)
        if running ; then
            echo "sentinel-daemon is running"
            exit 0
        else
            echo "sentinel-daemon is not running"
            exit 3
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/sentinel {start|stop|restart|status}" >&2
        exit 3
esac
